---
functional:
- требование 1 Пользователь должен иметь возможность искать товары по категории
- требование 2 Страница приложения должна иметь мобильную версию
- требование 3 Сайт должен открываться на различных устройствах
- требование 4 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- требование 5 Пользователь должен иметь возможность добавлять товары в корзину
- требование 6 Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру
- требование 7 Пользователь должен иметь возможность искать товары по ключевым словам
- требование 8 Пользователь должен иметь возможность менять количество товаров находясь в корзине
- требование 9 Невозможно оформить заказ с пустой корзиной
- требование 10 Пользователь должен иметь возможностьпросматривать товары в корзине
non-functional:
- требование 11 Понятность и привлекательность интерфейса
- требование 12 Кросс-браузерная совместимость
- требование 13 Сайт должен быть протестирован на совместимость с последними версиями браузеров
- требование 14 Сайт должен быть безопасным и защищать данные пользователя
- требование 15 Сайт должен отражать информацию на английском языке
- требование 16 Сайт должен отражать информацию на русском языке
implicit:
- требование 17 В списке производители, каждый производитель прописан единожды
- требование 18 В строке цена можно ввести только положительное значение 
- требование 19 В строке поиск можно искать товар как на английском, так и на русском языке
- требование 20 Можно вывести товары всех категорий сразу и осуществлять поиск из всех категорий товаров
- требование 21 Можно вывести товары всех брендов сразу, нажатием одной клавиши





