---
functional:
- требование 1 Пользователь должен иметь возможность искать товары по категории
- требование 2 Пользователь должен иметь возможность искать товары по ключевым словам
- требование 3 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- требование 4 Пользователь должен иметь возможность добавлять товары в корзину
- требование 5 Пользователь должен иметь возможность просматривать товары в корзине
- требование 6 Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру
- требование 7 Пользователь должен иметь возможность фильтровать товары по наличию
- требование 8 Пользователь должен иметь возможность менять количество товаров находясь в корзине
- требование 9 Невозможно оформить заказ с пустой корзиной
- требование 10 Страница приложения должна иметь мобильную версию
- требование 11 Сайт должен открываться на различных устройствах
non-functional:
- требование 12 Понятность и привлекательность интерфейса
- требование 13 Кросс-браузерная совместимость
- требование 14 Сайт должен быть протестирован на совместимость с последними версиями браузеров
- требование 15 Сайт должен быть безопасным и защищать данные пользователя
- требование 16 Сайт должен отражать информацию на английском языке
- требование 17 Сайт должен отражать информацию на русском языке
implicit:
- требование 18 В списке брендов, каждый бренд прописан единожды
- требование 19 В строке цена можно ввести только положительное значение 
- требование 20 В строке поиск можно искать товар как на английском, так и на русском языке
- требование 21 Можно вывести товары всех категорий сразу и осуществлять поиск из всех категорий товаров
- требование 22 Можно вывести товары всех брендов сразу, нажатием одной клавиши





